Repository infor-design/enterprise-wc, pull requests merged in 2024-07, with the labels that each got.

#2493 2347 - IdsSwitch design update
  doc/CHANGELOG.md
  src/components/ids-switch/demos/example.html
  src/components/ids-switch/ids-switch.scss
  src/components/ids-switch/ids-switch.ts
  src/themes/default/ids-theme-default-core.scss
  src/themes/mixins/ids-switch-mixin.scss
  tests/ids-switch/snapshots/switch-shadow.snap
Labels: Needs QA

#2511 2509 - Fix gen AI background color in dark mode
  doc/CHANGELOG.md
  src/components/ids-button/ids-button-base.scss
  src/themes/default/ids-theme-default-core.scss
  src/themes/default/ids-theme-default-dark.scss
Labels: Needs QA

#2512 2001 - IdsDropdown size and position
  doc/CHANGELOG.md
  src/components/ids-dropdown/demos/in-action-panel.html
  src/components/ids-dropdown/demos/in-action-panel.ts
  src/components/ids-dropdown/demos/in-expandable-area.html
  src/components/ids-dropdown/demos/in-expandable-area.ts
  src/components/ids-dropdown/demos/index.yaml
  src/components/ids-dropdown/ids-dropdown-list.ts
  src/components/ids-dropdown/ids-dropdown.ts
  src/components/ids-expandable-area/ids-expandable-area.scss
  src/mixins/ids-popup-open-events-mixin/ids-popup-open-events-mixin.ts
Labels: Needs QA

#2447 2429 - Loading indicator fixes
  doc/CHANGELOG.md
  src/components/ids-loading-indicator/demos/example.html
  src/components/ids-loading-indicator/demos/example.ts
  src/components/ids-loading-indicator/demos/side-by-side.html
  src/components/ids-loading-indicator/ids-loading-indicator.ts
Labels: Needs QA

#2530 2529 - Add css variables for accordion header padding
  doc/CHANGELOG.md
  src/components/ids-accordion/ids-accordion-header.scss
  src/components/ids-accordion/ids-accordion-panel.scss
  src/themes/default/ids-theme-default-core.scss
Labels: Needs QA

#2552 2462 - IdsDropdown tooltip zindex
  doc/CHANGELOG.md
  src/components/ids-dropdown/demos/in-action-panel.html
  src/components/ids-popup/ids-popup.scss
  src/themes/default/ids-theme-default-core.scss
Labels: Needs QA

#2496 2411 - IdsLayoutGrid responsive layout inside splitter
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  doc/CHANGELOG.md
  package.json
  src/assets/css/ids-layout-grid/example-inbox.css
  src/components/ids-hidden/README.md
  src/components/ids-hidden/ids-hidden.scss
  src/components/ids-hidden/ids-hidden.ts
  src/components/ids-layout-grid/README.md
  src/components/ids-layout-grid/demos/example-inbox.html
  src/components/ids-layout-grid/demos/example-inbox.ts
  src/components/ids-layout-grid/demos/example.html
  src/components/ids-layout-grid/demos/index.yaml
  src/components/ids-layout-grid/ids-layout-grid-base.scss
  src/components/ids-layout-grid/ids-layout-grid-cell.ts
  src/components/ids-layout-grid/ids-layout-grid-common.ts
  src/components/ids-layout-grid/ids-layout-grid-media-queries.scss
  src/components/ids-layout-grid/ids-layout-grid-mixins.scss
  src/components/ids-layout-grid/ids-layout-grid-responsive.scss
  src/components/ids-layout-grid/ids-layout-grid.scss
  src/components/ids-layout-grid/ids-layout-grid.ts
  src/components/ids-search-field/demos/example.html
  src/components/ids-splitter/ids-splitter.scss
  src/components/ids-splitter/ids-splitter.ts
  src/components/ids-trigger-field/ids-trigger-button.scss
  src/core/ids-attributes.ts
  tests/ids-color/ids-color.spec.ts
  tests/ids-container/ids-container.spec.ts
  tests/ids-counts/ids-counts.spec.ts
  tests/ids-data-grid/ids-data-grid.spec.ts
  tests/ids-layout-grid/ids-layout-grid.spec.ts
  tests/ids-menu-button/ids-menu-button.spec.ts
  tests/ids-personalize/ids-personalize.spec.ts
  tests/ids-splitter/snapshots/splitter-html.snap
Labels: Needs QA

#2533 2323 - IdsButton Notification badges
  doc/CHANGELOG.md
  src/components/ids-button/README.md
  src/components/ids-button/demos/index.yaml
  src/components/ids-button/demos/notification-badge.html
  src/components/ids-button/ids-button-base.scss
  src/components/ids-button/ids-button-common.ts
  src/components/ids-button/ids-button.scss
  src/components/ids-button/ids-button.ts
  src/components/ids-icon/ids-icon.scss
  src/components/ids-icon/ids-icon.ts
  src/components/ids-module-nav/ids-module-nav-settings.scss
  tests/ids-button/ids-button.spec.ts
Labels: Needs QA

#2580 2248 - IdsDropdown fix size setting for angular
  doc/CHANGELOG.md
  src/components/ids-dropdown/ids-dropdown-attributes-mixin.ts
  src/components/ids-dropdown/ids-dropdown.ts
Labels: Needs QA

#2592 2583 - Add fix for splitter text issue
  doc/CHANGELOG.md
  src/components/ids-splitter/demos/expand-collapse.html
  src/components/ids-splitter/demos/expand-collapse.ts
  src/components/ids-splitter/ids-splitter-pane.scss
  src/components/ids-splitter/ids-splitter-pane.ts
  src/components/ids-splitter/ids-splitter.scss
Labels: Needs QA

#2594 2586 - Added new method `resetDirtyRow` allowing to reset dirty state for an specific row
  doc/CHANGELOG.md
  src/components/ids-data-grid/ids-data-grid.ts
  tests/ids-data-grid/ids-data-grid-editing.spec.ts
Labels: Needs QA

#2584 2582 - IdsDropdown position in tabs
  doc/CHANGELOG.md
  src/components/ids-data-grid/demos/in-tabs.html
  src/components/ids-data-grid/demos/in-tabs.ts
  src/components/ids-data-grid/demos/index.yaml
  src/components/ids-data-grid/ids-data-grid-cell.scss
  src/components/ids-data-grid/ids-data-grid-editors.ts
  src/components/ids-dropdown/ids-dropdown-list.scss
  src/components/ids-dropdown/ids-dropdown-list.ts
Labels: Needs QA

#2614 2585/2590 - Fix initialize issues in splitter
  doc/CHANGELOG.md
  src/components/ids-splitter/ids-splitter-pane.ts
  tests/ids-splitter/ids-splitter.spec.ts
Labels: High, Needs QA

#2623 Chore: Add list test reporter
  package.json
Labels: status: wip :construction:
